package com.bdcrm.lead;

public enum LeadActivityType {
    LEAD_CREATED,
    LEAD_UPDATED,
    STATUS_CHANGED,
    ASSIGNED,
    NOTE_ADDED,
    FOLLOWUP_COMPLETED,
    FOLLOWUP_RESCHEDULED,
    FOLLOWUP_SKIPPED,
    FOLLOWUP_REASSIGNED,
    FOLLOWUP_ESCALATED,
    FOLLOWUPS_CLOSED
}
