package com.bdcrm.lead;

public enum LeadActivityType {
    LEAD_CREATED,
    LEAD_UPDATED,
    STATUS_CHANGED,
    STAGE_CHANGED,
    ASSIGNED,
    NOTE_ADDED,
    QUALIFICATION_UPDATED,
    COMMUNICATION_LOGGED,
    ATTACHMENT_ADDED,
    DOCUMENT_UPDATED,
    DUPLICATE_FLAGGED,
    LEAD_MERGED,
    FOLLOWUP_COMPLETED,
    FOLLOWUP_RESCHEDULED,
    FOLLOWUP_SKIPPED,
    FOLLOWUP_REASSIGNED,
    FOLLOWUP_ESCALATED,
    FOLLOWUPS_CLOSED
}
